### ISSUE TITLE
Better name

### ISSUE THREAD

**Issue by miloskroulik** [lulco/adminerng#17]
Current name is too long (and has a typo). What about **Uniman** (because of universal manager)? There [isn't anything with that name on GH](https://github.com/search?utf8=%E2%9C%93&q=uniman), yet.

**Comment by vrana** [comment]
I am the author of Adminer and I agree. Please change the name to something else. Similar names are confusing for users and they cause other problems.

**Comment by lulco** [comment]
I just renamed repository to uniman. @miloskroulik thanks for suggestion :) 
All other changes (in source code) I will do when I will find some time for open source projects

**Comment by miloskroulik** [comment]
I'm glad it was useful for you! Good luck with the project :-)

**Comment by vrana** [comment]
Please rename at least the title in README.

**Comment by vrana** [comment]
There are still three more occurences: https://github.com/lulco/uniman/search?q=Adminer
